name: Build1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Import certificates and provisioning profile
      env:
        DEVELOPER_ID_APPLICATION_CERT: ${{ secrets.DEVELOPER_ID_APPLICATION_CERT }}
        DEVELOPER_ID_APPLICATION_PASSWORD: ${{ secrets.DEVELOPER_ID_APPLICATION_PASSWORD }}
        PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE }}
      run: |
        # Create keychain
        security create-keychain -p "" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "" build.keychain
        security set-keychain-settings -t 3600 -l build.keychain
    
        echo "$DEVELOPER_ID_APPLICATION_CERT" | base64 --decode > certificate.p12
        security import certificate.p12 -k build.keychain -P "$DEVELOPER_ID_APPLICATION_PASSWORD" -T /usr/bin/codesign -A
    
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        echo "$PROVISIONING_PROFILE" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/Pricey_Developer_ID_Application.provisionprofile
    
        security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
        
        # List identities to verify import
        security find-identity -v -p codesigning build.keychain

    - name: Build app
      run: |
        xcodebuild -scheme Pricey -configuration Release -derivedDataPath build CODE_SIGN_IDENTITY="Developer ID Application: Goose Wrappers UG (haftungsbeschrankt)" PROVISIONING_PROFILE_SPECIFIER="Pricey Developer ID Application" DEVELOPMENT_TEAM="6TMG4Q64WM" clean build
        
    - name: Create app bundle
      run: |
        mkdir -p dist
        cp -R build/Build/Products/Release/Pricey.app dist/
        
    - name: Create DMG
      run: |
        # Create a temporary directory for DMG contents
        mkdir -p dmg_contents
        cp -R dist/Pricey.app dmg_contents/
        
        # Create a symbolic link to Applications folder
        ln -sf /Applications dmg_contents/Applications
        
        # Create the DMG
        hdiutil create -volname "Pricey" -srcfolder dmg_contents -ov -format UDZO Pricey.dmg
        
    - name: Upload DMG as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Pricey-DMG
        path: Pricey.dmg

    - name: Upload DMG to release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./Pricey.dmg
        asset_name: Pricey.dmg
        asset_content_type: application/octet-stream

