name: Build1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Import certificates and provisioning profile
      env:
        APPLE_WWDR_CERT: ${{ secrets.APPLE_WWDR_CERT }}
        DEVELOPER_ID_APPLICATION_CERT: ${{ secrets.DEVELOPER_ID_APPLICATION_CERT }}
        DEVELOPER_ID_APPLICATION_PASSWORD: ${{ secrets.DEVELOPER_ID_APPLICATION_PASSWORD }}
        PROVISIONING_PROFILE: ${{ secrets.PROVISIONING_PROFILE }}
      run: |
        # Create keychain
        security create-keychain -p "" build.keychain
        security default-keychain -s build.keychain
        security unlock-keychain -p "" build.keychain

        echo -n "$APPLE_WWDR_CERT" | base64 --decode > apple_wwdr.cer
        security import apple_wwdr.cer -k build.keychain -T /usr/bin/codesign
    
        echo -n "$DEVELOPER_ID_APPLICATION_CERT" | base64 --decode > certificate.p12
        security import certificate.p12 -k build.keychain -P "$DEVELOPER_ID_APPLICATION_PASSWORD" -A -t cert -f pkcs12

        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        echo "$PROVISIONING_PROFILE" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/Pricey_Developer_ID_Application.provisionprofile
    
        security dump-keychain build.keychain
        security list-keychain -d user -s build.keychain

        security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain
        
        # List identities to verify import
        security find-identity -v -p codesigning

        security default-keychain -s build.keychain

    - name: Build app
      run: |
        xcodebuild \
          -scheme Pricey \
          -configuration Release \
          -derivedDataPath build \
          CODE_SIGN_IDENTITY="Developer ID Application: Goose Wrappers UG (haftungsbeschrankt)" \
          PROVISIONING_PROFILE_SPECIFIER="Pricey Developer ID Application" \
          DEVELOPMENT_TEAM="6TMG4Q64WM" \
          clean build
        
    - name: Create app bundle
      run: |
        mkdir -p dist
        cp -R build/Build/Products/Release/Pricey.app dist/
        cd dist
        zip -rp9 ../Pricey-darwin-arm64.zip Pricey.app
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Pricey
        path: Pricey-darwin-arm64.zip

    - name: Upload DMG to release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./Pricey-darwin-arm64.zip
        asset_name: Pricey-darwin-arm64.zip
        asset_content_type: application/octet-stream

