name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable

    - name: Build app
      run: |
        xcodebuild -scheme Pricey -configuration Release -derivedDataPath build clean build
        
    - name: Create app bundle
      run: |
        mkdir -p dist
        cp -R build/Build/Products/Release/Pricey.app dist/
        
    - name: Create DMG
      run: |
        # Create a temporary directory for DMG contents
        mkdir -p dmg_contents
        cp -R dist/Pricey.app dmg_contents/
        
        # Create a symbolic link to Applications folder
        ln -sf /Applications dmg_contents/Applications
        
        # Create the DMG
        hdiutil create -volname "Pricey" -srcfolder dmg_contents -ov -format UDZO Pricey.dmg
        
    - name: Upload DMG as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Pricey-DMG
        path: Pricey.dmg

    - name: Upload DMG to release
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./Pricey.dmg
        asset_name: Pricey.dmg
        asset_content_type: application/octet-stream

